# Generated by Django 2.2 on 2019-04-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('public', models.BooleanField()),
                ('correct', models.BooleanField()),
                ('slug', models.SlugField()),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Added')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
